add redis for realtime/rate limiting
dymajo/waka-server pull request #25
Opened 2019-07-10 07:46 UTC by mjdavidson

2019-07-10 12:41 UTC, consindo commented
Looking good. I would however, take the opportunity to split this out into a new top level project, so we can run with the everything when doing dev locally, as a Docker container, or potentially as a lambda on a cron job.

2019-07-11 07:26 UTC, consindo commented on src/waka-realtime/index.ts
> +    this.prefix = config.prefix
I would probably also prepend a waka-rt- to the key too? Just in case we need to use it in other components.

2019-07-12 07:54 UTC, mjdavidson commented
you can have a look over this and merge when u want

2019-07-13 11:55 UTC, consindo requested changes
Functionality is excellent - well done! Well architected too, and just works with the orchestrator.

Only a couple of things:
- [x] Add a section to the readme about waka-realtime
- [x] I think `waka-worker/realtime/ProtobufRealtime.ts` needs to be deleted
- [x] If the Redis connection fails, it shouldn't crash the process, but rather just not do realtime.
- [x] As the Redis connection is made in the constructor, it makes it harder to unit test. I would move the connection to the `start()` method, and close it in the `stop()` method.
- [x] You'll need to add redis configuration support to the configManager or something, otherwise we won't be able to use elasticache. It would be good if you could implement in a similar way to the database connections (i.e pointers to configs)

2019-07-15 11:25 UTC, consindo approved these changes

2019-07-15 12:33 UTC, merged